services:
  app:
    build: .
    container_name: laravel-simple-app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    depends_on:
      - db
    networks:
      - laravel-simple

  db:
    image: mysql:5.7
    container_name: laravel-simple-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_simple
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-simple

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1
    container_name: laravel-simple-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: secret
    depends_on:
      - db
    networks:
      - laravel-simple

volumes:
  vendor:
  node_modules:
  mysql_data:

networks:
  laravel-simple:
    driver: bridge
